// <auto-generated />
using System;
using ContentsLimitInsurance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContentsLimitInsurance.Migrations
{
    [DbContext(typeof(ContentsLimitContext))]
    partial class ContentsLimitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("ContentsLimitInsurance.Data.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatePurchased")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e97b124c-b09f-4bd1-93c1-b748032d37fe"),
                            AssetCategoryId = new Guid("64bc457a-e276-4ff4-ac5f-fbf0511eb5ab"),
                            DatePurchased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "Living Room",
                            Name = "TV",
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("d816f69f-fdee-426f-82ad-cae9da9657a9"),
                            AssetCategoryId = new Guid("64bc457a-e276-4ff4-ac5f-fbf0511eb5ab"),
                            DatePurchased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "Living Room",
                            Name = "Playstation",
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("dd7cf440-df22-46d5-ba1b-5e56f15bd581"),
                            AssetCategoryId = new Guid("64bc457a-e276-4ff4-ac5f-fbf0511eb5ab"),
                            DatePurchased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "Bedroom",
                            Name = "Stereo",
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("11a963a8-2308-4e6c-9043-ecb28363f8e6"),
                            AssetCategoryId = new Guid("3b2320c7-8267-4b98-9593-702b1eb2e2cf"),
                            DatePurchased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "Bedroom",
                            Name = "Shirts",
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("0edf63d2-d93c-4b76-b902-d7beaad4566f"),
                            AssetCategoryId = new Guid("3b2320c7-8267-4b98-9593-702b1eb2e2cf"),
                            DatePurchased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "Bedroom",
                            Name = "Jeans",
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("e5b4d8cf-1c15-49e2-93a3-29064d91847e"),
                            AssetCategoryId = new Guid("44a4685a-9485-486b-b8d9-75553fb6f3f0"),
                            DatePurchased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "Kitchen",
                            Name = "Pots and Pans",
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("6c25f943-04ae-4366-b9c7-ea43497e424c"),
                            AssetCategoryId = new Guid("44a4685a-9485-486b-b8d9-75553fb6f3f0"),
                            DatePurchased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "Kitchen",
                            Name = "Flatware",
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("4a04e950-7c79-4558-b810-1b46a15cf2b9"),
                            AssetCategoryId = new Guid("44a4685a-9485-486b-b8d9-75553fb6f3f0"),
                            DatePurchased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "Kitchen",
                            Name = "Knife Set",
                            Value = 0.0
                        },
                        new
                        {
                            Id = new Guid("cdbc989b-7545-486e-b7c4-26a453444e9a"),
                            AssetCategoryId = new Guid("44a4685a-9485-486b-b8d9-75553fb6f3f0"),
                            DatePurchased = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Location = "Kitchen",
                            Name = "Misc",
                            Value = 0.0
                        });
                });

            modelBuilder.Entity("ContentsLimitInsurance.Data.Entities.AssetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64bc457a-e276-4ff4-ac5f-fbf0511eb5ab"),
                            IsDeleted = false,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("3b2320c7-8267-4b98-9593-702b1eb2e2cf"),
                            IsDeleted = false,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("44a4685a-9485-486b-b8d9-75553fb6f3f0"),
                            IsDeleted = false,
                            Name = "Kitchen"
                        });
                });

            modelBuilder.Entity("ContentsLimitInsurance.Data.Entities.Asset", b =>
                {
                    b.HasOne("ContentsLimitInsurance.Data.Entities.AssetCategory", "AssetCategory")
                        .WithMany("Assets")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
